services:
  app:
    command: ["wait-for-it.sh", "postgres:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - 8000:8000 
    volumes:
      - ../:/opt/app
    working_dir: /opt/app/src
